// adapters/vue/components/FdyDateRange.vue
<script lang="ts">
export interface DateRangeValue {
  start: string | null;
  end: string | null;
}
</script>

<script setup lang="ts">
import { computed, type ComputedRef } from 'vue';
import FdyDatepicker from './FdyDatepicker.vue';

// A controlled date range over freeday's `.fdy-daterange` layout (src/components/datepicker.css):
// two linked FdyDatepickers where the end can't precede the start (start.max = end, end.min =
// start). A real `v-model:DateRangeValue` that composes the single-date picker rather than
// re-implementing the calendar. The vanilla enhancer's cross-calendar `.in-range` day shading is
// not reproduced (each picker is independent), the min/max linkage is what keeps the range valid.

const props = defineProps<{
  modelValue: DateRangeValue;
  min?: string;
  max?: string;
  locale?: string;
  disabled?: boolean;
  /** Locked/view mode for both pickers — focusable, values shown, but can't be opened or changed. */
  readonly?: boolean;
  invalid?: boolean;
  describedby?: string;
  startPlaceholder?: string;
  endPlaceholder?: string;
  ariaLabel?: string;
  ariaLabelledby?: string;
}>();

const emit = defineEmits<{
  'update:modelValue': [value: DateRangeValue];
  change: [value: DateRangeValue];
}>();

const startMax: ComputedRef<string | undefined> = computed((): string | undefined => props.modelValue.end ?? props.max);
const endMin: ComputedRef<string | undefined> = computed((): string | undefined => props.modelValue.start ?? props.min);

function setStart(start: string): void {
  const next: DateRangeValue = { start, end: props.modelValue.end };
  emit('update:modelValue', next);
  emit('change', next);
}
function setEnd(end: string): void {
  const next: DateRangeValue = { start: props.modelValue.start, end };
  emit('update:modelValue', next);
  emit('change', next);
}
</script>

<template>
  <div class="fdy-daterange" role="group" :aria-label="ariaLabel" :aria-labelledby="ariaLabelledby">
    <FdyDatepicker
      :model-value="modelValue.start"
      :min="min"
      :max="startMax"
      :locale="locale"
      :disabled="disabled"
      :readonly="readonly"
      :invalid="invalid"
      :describedby="describedby"
      :placeholder="startPlaceholder ?? 'Dari'"
      @update:model-value="setStart"
    />
    <span class="fdy-daterange__sep" aria-hidden="true">–</span>
    <FdyDatepicker
      :model-value="modelValue.end"
      :min="endMin"
      :max="max"
      :locale="locale"
      :disabled="disabled"
      :readonly="readonly"
      :invalid="invalid"
      :describedby="describedby"
      :placeholder="endPlaceholder ?? 'Sampai'"
      @update:model-value="setEnd"
    />
  </div>
</template>

// adapters/react/components/FdyDateRange.tsx
import type { JSX } from 'react';
import { FdyDatepicker } from './FdyDatepicker';

// A controlled date range over freeday's `.fdy-daterange` layout (src/components/datepicker.css):
// two linked FdyDatepickers where the end can't precede the start (start.max = end, end.min = start).
// `value` + `onChange` in place of Vue's `v-model`; this composes the single-date picker rather than
// re-implementing the calendar. Note: the vanilla enhancer's cross-calendar `.in-range` day shading
// is not reproduced (each picker is independent), the min/max linkage is what keeps the range valid.

export interface DateRangeValue {
  start: string | null;
  end: string | null;
}

export interface FdyDateRangeProps {
  value: DateRangeValue;
  onChange: (value: DateRangeValue) => void;
  min?: string;
  max?: string;
  locale?: string;
  disabled?: boolean;
  /** Locked/view mode for both pickers, focusable, values shown, but can't be opened or changed. */
  readonly?: boolean;
  invalid?: boolean;
  describedby?: string;
  startPlaceholder?: string;
  endPlaceholder?: string;
  ariaLabel?: string;
  ariaLabelledby?: string;
}

export function FdyDateRange(props: FdyDateRangeProps): JSX.Element {
  const onStart = (start: string): void => props.onChange({ start, end: props.value.end });
  const onEnd = (end: string): void => props.onChange({ start: props.value.start, end });

  return (
    <div
      className="fdy-daterange"
      role="group"
      aria-label={props.ariaLabel}
      aria-labelledby={props.ariaLabelledby}
    >
      <FdyDatepicker
        value={props.value.start}
        onChange={onStart}
        min={props.min}
        max={props.value.end ?? props.max}
        locale={props.locale}
        disabled={props.disabled}
        readonly={props.readonly}
        invalid={props.invalid}
        describedby={props.describedby}
        placeholder={props.startPlaceholder ?? 'Dari'}
      />
      <span className="fdy-daterange__sep" aria-hidden="true">–</span>
      <FdyDatepicker
        value={props.value.end}
        onChange={onEnd}
        min={props.value.start ?? props.min}
        max={props.max}
        locale={props.locale}
        disabled={props.disabled}
        readonly={props.readonly}
        invalid={props.invalid}
        describedby={props.describedby}
        placeholder={props.endPlaceholder ?? 'Sampai'}
      />
    </div>
  );
}
