// adapters/react/components/FdyDatepicker.tsx
import type { JSX } from 'react';
import { useEffect, useId, useMemo, useRef, useState } from 'react';
import { usePopover } from '../usePopover';

// React port of adapters/vue/components/FdyDatepicker.vue over freeday's `.fdy-datepicker` /
// `.fdy-cal__*` classes (see src/components/datepicker.css). Re-implements the single-date
// calendar behavior (month grid, keyboard nav, min/max clamping, Intl locale formatting) as a
// controlled React component (`value` + `onChange` in place of Vue's `v-model`). Open/close
// (outside-click + focusout) mirrors the already-approved FdyCombo.tsx pattern. Range mode is
// out of scope (v1 = single date).

interface DayCell {
  date: Date;
  iso: string;
  label: number;
  ariaLabel: string;
  outside: boolean;
  today: boolean;
  selected: boolean;
  disabled: boolean;
  focusable: boolean;
}

interface YearCell {
  year: number;
  selected: boolean;
  today: boolean;
  disabled: boolean;
  focusable: boolean;
}

interface MonthCell {
  index: number;
  label: string;
  ariaLabel: string;
  selected: boolean;
  today: boolean;
  disabled: boolean;
  focusable: boolean;
}

export interface FdyDatepickerProps {
  value: string | null;
  onChange: (value: string) => void;
  min?: string;
  max?: string;
  locale?: string;
  placeholder?: string;
  disabled?: boolean;
  /** Locked/view mode: stays focusable and shows its date, but can't be opened, cleared, or changed. Unlike `disabled`, it keeps tab order and isn't greyed. */
  readonly?: boolean;
  invalid?: boolean;
  describedby?: string;
  id?: string;
  ariaLabelledby?: string;
  /** Show a clear (×) button in the trigger when a date is set, so an optional date can be unset. Calls onChange('') to reset. Off by default. */
  clearable?: boolean;
  /** aria-label for the previous-month nav button. Default 'Previous month' — override for non-English UIs (month/weekday names already follow `locale`). */
  /** aria-label for the title button that drills to the month grid. Default 'Choose month'. */
  chooseMonthLabel?: string;
  /** aria-labels for the year arrows shown in the month grid. Defaults 'Previous year' / 'Next year'. */
  prevYearLabel?: string;
  nextYearLabel?: string;
  /** aria-label for the title button that drills from the month grid to the year grid. Default 'Choose year'. */
  chooseYearLabel?: string;
  /** aria-labels for the page arrows shown in the year grid. Defaults 'Previous years' / 'Next years'. */
  prevYearsLabel?: string;
  nextYearsLabel?: string;
  prevMonthLabel?: string;
  /** aria-label for the next-month nav button. Default 'Next month'. */
  nextMonthLabel?: string;
  /** aria-label for the clear button (when `clearable`). Default 'Clear date'. */
  clearLabel?: string;
}

function pad(n: number): string {
  return n < 10 ? `0${n}` : `${n}`;
}
function toISO(d: Date): string {
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}`;
}
function parseISO(s: string | null | undefined): Date | null {
  if (s === null || s === undefined || s === '') return null;
  const parts: string[] = s.split('-');
  if (parts.length !== 3) return null;
  const y: number = Number(parts[0]);
  const m: number = Number(parts[1]);
  const day: number = Number(parts[2]);
  const d: Date = new Date(y, m - 1, day);
  return Number.isNaN(d.getTime()) ? null : d;
}
function startOfDay(d: Date): Date {
  return new Date(d.getFullYear(), d.getMonth(), d.getDate());
}
function startOfMonth(d: Date): Date {
  return new Date(d.getFullYear(), d.getMonth(), 1);
}
function sameDay(a: Date | null, b: Date | null): boolean {
  return a !== null && b !== null && a.getFullYear() === b.getFullYear() && a.getMonth() === b.getMonth() && a.getDate() === b.getDate();
}
function addDays(d: Date, n: number): Date {
  const x: Date = new Date(d);
  x.setDate(x.getDate() + n);
  return x;
}
function addMonths(d: Date, n: number): Date {
  const x: Date = new Date(d);
  x.setMonth(x.getMonth() + n);
  return x;
}

function dayClassName(cell: DayCell): string {
  let cls = 'fdy-cal__day';
  if (cell.outside) cls += ' is-outside';
  if (cell.today) cls += ' is-today';
  if (cell.selected) cls += ' is-selected';
  return cls;
}

export function FdyDatepicker(props: FdyDatepickerProps): JSX.Element {
  const baseId: string = useId();
  const triggerId: string = props.id ?? `${baseId}-trigger`;
  const titleId: string = `${baseId}-title`;

  const rootRef = useRef<HTMLDivElement>(null);
  const triggerRef = useRef<HTMLButtonElement>(null);
  const panelRef = useRef<HTMLDivElement>(null);
  const dayRefs = useRef<Record<string, HTMLButtonElement | null>>({});
  // Set by moveFocus/openPanel, consumed by the focus-sync effect below (React's analogue of
  // Vue's `nextTick(focusCell)`); nav-button clicks intentionally leave this untouched so they
  // don't steal DOM focus off the button, matching the Vue template's behavior.
  const pendingFocusRef = useRef<string | null>(null);

  const [open, setOpen] = useState<boolean>(false);
  /* 'days' | 'months' — the calendar drills one level up instead of growing furniture beside the
     title. Before this the only pointer route to another month was one click per month. */
  const [mode, setMode] = useState<'days' | 'months' | 'years'>('days');
  const [focusMonth, setFocusMonth] = useState<number>(0);
  const [focusYear, setFocusYear] = useState<number>(0);

  /* A page of twelve years, ALIGNED so pages tile: 2016-2027, 2028-2039. Anchoring on the year in
     view would make the arrows land on overlapping windows, and the same year would sit somewhere
     different every step. */
  const YEARS_PER_PAGE = 12;
  const yearPageStart = (year: number): number => Math.floor(year / YEARS_PER_PAGE) * YEARS_PER_PAGE;
  const monthRefs = useRef<Record<number, HTMLButtonElement | null>>({});
  const pendingMonthFocusRef = useRef<number | null>(null);
  const yearRefs = useRef<Record<number, HTMLButtonElement | null>>({});
  const pendingYearFocusRef = useRef<number | null>(null);

  // Render the calendar panel in the top layer (popover) so it never gets clipped by a card or
  // scroll container; positions against the trigger.
  usePopover(panelRef, triggerRef, open);

  // Popover attr for React 18 (JSX may not type it): set once on mount.
  useEffect((): void => {
    panelRef.current?.setAttribute('popover', 'manual');
  }, []);

  const selectedDate: Date | null = useMemo((): Date | null => parseISO(props.value), [props.value]);
  const minDate: Date | null = useMemo((): Date | null => parseISO(props.min), [props.min]);
  const maxDate: Date | null = useMemo((): Date | null => parseISO(props.max), [props.max]);
  const isDisabled: boolean = props.disabled === true;
  const isReadonly: boolean = props.readonly === true;
  const isInvalid: boolean = props.invalid === true;
  const displayPlaceholder: string = props.placeholder ?? 'Select date';
  const showClear: boolean = props.clearable === true && selectedDate !== null && !isDisabled && !isReadonly;
  const chooseMonthLabelText: string = props.chooseMonthLabel ?? 'Choose month';
  const prevYearLabelText: string = props.prevYearLabel ?? 'Previous year';
  const nextYearLabelText: string = props.nextYearLabel ?? 'Next year';
  const chooseYearLabelText: string = props.chooseYearLabel ?? 'Choose year';
  const prevYearsLabelText: string = props.prevYearsLabel ?? 'Previous years';
  const nextYearsLabelText: string = props.nextYearsLabel ?? 'Next years';
  const monthCellFmt: Intl.DateTimeFormat = useMemo(
    (): Intl.DateTimeFormat => new Intl.DateTimeFormat(props.locale, { month: 'short' }),
    [props.locale],
  );
  const monthNameFmt: Intl.DateTimeFormat = useMemo(
    (): Intl.DateTimeFormat => new Intl.DateTimeFormat(props.locale, { month: 'long', year: 'numeric' }),
    [props.locale],
  );
  const prevMonthLabelText: string = props.prevMonthLabel ?? 'Previous month';
  const nextMonthLabelText: string = props.nextMonthLabel ?? 'Next month';
  const clearLabelText: string = props.clearLabel ?? 'Clear date';

  const [viewMonth, setViewMonth] = useState<Date>((): Date => startOfMonth(parseISO(props.value) ?? new Date()));
  const [focusDate, setFocusDate] = useState<Date>((): Date => parseISO(props.value) ?? new Date());

  // Keep the roving-tabindex cell inside the visible month so the grid stays keyboard-reachable
  // after navigating with Home/End/PageUp/PageDown (mirrors freeday-datepicker.js's clamp).
  const effectiveFocusDate: Date = useMemo((): Date => {
    if (focusDate.getMonth() === viewMonth.getMonth() && focusDate.getFullYear() === viewMonth.getFullYear()) return focusDate;
    const daysInMonth: number = new Date(viewMonth.getFullYear(), viewMonth.getMonth() + 1, 0).getDate();
    return new Date(viewMonth.getFullYear(), viewMonth.getMonth(), Math.min(focusDate.getDate(), daysInMonth));
  }, [focusDate, viewMonth]);

  const monthFmt: Intl.DateTimeFormat = useMemo(
    (): Intl.DateTimeFormat => new Intl.DateTimeFormat(props.locale, { month: 'long', year: 'numeric' }),
    [props.locale],
  );
  const valueFmt: Intl.DateTimeFormat = useMemo(
    (): Intl.DateTimeFormat => new Intl.DateTimeFormat(props.locale, { day: '2-digit', month: 'short', year: 'numeric' }),
    [props.locale],
  );
  const dayLabelFmt: Intl.DateTimeFormat = useMemo(
    (): Intl.DateTimeFormat => new Intl.DateTimeFormat(props.locale, { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' }),
    [props.locale],
  );
  const dowFmt: Intl.DateTimeFormat = useMemo(
    (): Intl.DateTimeFormat => new Intl.DateTimeFormat(props.locale, { weekday: 'short' }),
    [props.locale],
  );

  const displayValue: string = selectedDate !== null ? valueFmt.format(selectedDate) : displayPlaceholder;

  const weekdayHeaders: string[] = useMemo((): string[] => {
    const monday: Date = new Date(2024, 0, 1); // a known Monday
    return Array.from({ length: 7 }, (_unused: unknown, i: number): string => dowFmt.format(addDays(monday, i)));
  }, [dowFmt]);

  function isDayDisabled(d: Date): boolean {
    if (minDate !== null && startOfDay(d).getTime() < startOfDay(minDate).getTime()) return true;
    if (maxDate !== null && startOfDay(d).getTime() > startOfDay(maxDate).getTime()) return true;
    return false;
  }

  /** A month is only unreachable when the WHOLE month falls outside min/max — a range that sits
   *  inside one month disables both ends while the middle is perfectly selectable. */
  function isMonthDisabled(year: number, month: number): boolean {
    const first: Date = new Date(year, month, 1);
    const last: Date = new Date(year, month + 1, 0);
    if (minDate !== null && startOfDay(last).getTime() < startOfDay(minDate).getTime()) return true;
    if (maxDate !== null && startOfDay(first).getTime() > startOfDay(maxDate).getTime()) return true;
    return false;
  }

  const monthCells: MonthCell[] = useMemo((): MonthCell[] => {
    const year: number = viewMonth.getFullYear();
    const today: Date = new Date();
    const sel: Date | null = parseISO(props.value);
    return Array.from({ length: 12 }, (_unused: unknown, index: number): MonthCell => {
      const cellDate: Date = new Date(year, index, 1);
      return {
        index,
        label: monthCellFmt.format(cellDate),
        ariaLabel: monthNameFmt.format(cellDate),
        selected: sel !== null && sel.getFullYear() === year && sel.getMonth() === index,
        today: today.getFullYear() === year && today.getMonth() === index,
        disabled: isMonthDisabled(year, index),
        focusable: index === focusMonth,
      };
    });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [viewMonth, props.value, focusMonth, monthCellFmt, monthNameFmt, minDate, maxDate]);

  const gridCells: DayCell[] = useMemo((): DayCell[] => {
    const first: Date = new Date(viewMonth.getFullYear(), viewMonth.getMonth(), 1);
    const offset: number = (first.getDay() + 6) % 7; // Monday-first
    const startCell: Date = addDays(first, -offset);
    const today: Date = new Date();
    const focus: Date = effectiveFocusDate;
    const cells: DayCell[] = [];
    for (let i = 0; i < 42; i++) {
      const d: Date = addDays(startCell, i);
      cells.push({
        date: d,
        iso: toISO(d),
        label: d.getDate(),
        ariaLabel: dayLabelFmt.format(d),
        outside: d.getMonth() !== viewMonth.getMonth(),
        today: sameDay(d, today),
        selected: sameDay(d, selectedDate),
        disabled: isDayDisabled(d),
        focusable: sameDay(d, focus),
      });
    }
    return cells;
    // Deps intentionally mirror the port recipe, not every closure read: minDate/maxDate,
    // dayLabelFmt and effectiveFocusDate all derive deterministically from the listed deps
    // within the same render pass, so this stays in sync without listing them separately.
  }, [viewMonth, props.value, props.min, props.max, props.locale]);

  // Focus the roving-tabindex cell after a render triggered by moveFocus/openPanel (React's
  // analogue of Vue's `nextTick(focusCell)`). Runs after every render; cheap no-op otherwise.
  useEffect((): void => {
    if (pendingFocusRef.current === null) return;
    const iso: string = pendingFocusRef.current;
    pendingFocusRef.current = null;
    dayRefs.current[iso]?.focus();
  });

  useEffect((): void => {
    if (pendingMonthFocusRef.current === null) return;
    const index: number = pendingMonthFocusRef.current;
    pendingMonthFocusRef.current = null;
    monthRefs.current[index]?.focus();
  });

  useEffect((): void => {
    if (pendingYearFocusRef.current === null) return;
    const year: number = pendingYearFocusRef.current;
    pendingYearFocusRef.current = null;
    yearRefs.current[year]?.focus();
  });

  function openMonthGrid(): void {
    setFocusMonth(viewMonth.getMonth());
    setMode('months');
    pendingMonthFocusRef.current = viewMonth.getMonth();
  }

  /* Picking a month is NAVIGATION, not selection: back to the day grid with the roving cell clamped
     into the new month, so nothing is committed until a day is chosen. */
  function openMonth(index: number): void {
    const year: number = viewMonth.getFullYear();
    const daysInMonth: number = new Date(year, index + 1, 0).getDate();
    const next: Date = new Date(year, index, Math.min(focusDate.getDate(), daysInMonth));
    setViewMonth(new Date(year, index, 1));
    setFocusDate(next);
    setMode('days');
    pendingFocusRef.current = toISO(next);
  }

  function moveMonthFocus(index: number, yearDelta: number): void {
    if (yearDelta !== 0) setViewMonth(addMonths(viewMonth, yearDelta * 12));
    const next: number = (index + 12) % 12;
    setFocusMonth(next);
    pendingMonthFocusRef.current = next;
  }

  /** A year is unreachable only when EVERY month in it falls outside min/max. */
  function isYearDisabled(year: number): boolean {
    if (minDate !== null && startOfDay(new Date(year, 11, 31)).getTime() < startOfDay(minDate).getTime()) return true;
    if (maxDate !== null && startOfDay(new Date(year, 0, 1)).getTime() > startOfDay(maxDate).getTime()) return true;
    return false;
  }

  const yearPage: number = yearPageStart(focusYear);
  const yearRangeLabel: string = `${yearPage} – ${yearPage + YEARS_PER_PAGE - 1}`;

  const yearCells: YearCell[] = useMemo((): YearCell[] => {
    const start: number = yearPageStart(focusYear);
    const thisYear: number = new Date().getFullYear();
    const sel: Date | null = parseISO(props.value);
    return Array.from({ length: YEARS_PER_PAGE }, (_unused: unknown, index: number): YearCell => {
      const year: number = start + index;
      return {
        year,
        selected: sel !== null && sel.getFullYear() === year,
        today: thisYear === year,
        disabled: isYearDisabled(year),
        focusable: year === focusYear,
      };
    });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [focusYear, props.value, minDate, maxDate]);

  function openYearGrid(): void {
    setFocusYear(viewMonth.getFullYear());
    setMode('years');
    pendingYearFocusRef.current = viewMonth.getFullYear();
  }

  /* Picking a year is NAVIGATION, exactly like picking a month: it drops to that year's month grid
     and commits nothing. */
  function openYear(year: number): void {
    setViewMonth(new Date(year, viewMonth.getMonth(), 1));
    setFocusMonth(viewMonth.getMonth());
    setMode('months');
    pendingMonthFocusRef.current = viewMonth.getMonth();
  }

  function moveYearFocus(year: number): void {
    setFocusYear(year);
    setViewMonth(new Date(year, viewMonth.getMonth(), 1));
    pendingYearFocusRef.current = year;
  }

  function onYearKeydown(e: React.KeyboardEvent): void {
    let handled: boolean = true;
    switch (e.key) {
      case 'ArrowLeft': moveYearFocus(focusYear - 1); break;
      case 'ArrowRight': moveYearFocus(focusYear + 1); break;
      case 'ArrowUp': moveYearFocus(focusYear - 3); break;
      case 'ArrowDown': moveYearFocus(focusYear + 3); break;
      case 'Home': moveYearFocus(yearPageStart(focusYear)); break;
      case 'End': moveYearFocus(yearPageStart(focusYear) + YEARS_PER_PAGE - 1); break;
      case 'PageUp': moveYearFocus(focusYear - YEARS_PER_PAGE); break;
      case 'PageDown': moveYearFocus(focusYear + YEARS_PER_PAGE); break;
      case 'Enter':
      case ' ': openYear(focusYear); break;
      case 'Escape': closePanel(true); break;
      default: handled = false;
    }
    if (handled) { e.preventDefault(); e.stopPropagation(); }
  }

  function onMonthKeydown(e: React.KeyboardEvent): void {
    let handled: boolean = true;
    switch (e.key) {
      case 'ArrowLeft': moveMonthFocus(focusMonth - 1, 0); break;
      case 'ArrowRight': moveMonthFocus(focusMonth + 1, 0); break;
      case 'ArrowUp': moveMonthFocus(focusMonth - 3, 0); break;
      case 'ArrowDown': moveMonthFocus(focusMonth + 3, 0); break;
      case 'Home': moveMonthFocus(0, 0); break;
      case 'End': moveMonthFocus(11, 0); break;
      case 'PageUp': moveMonthFocus(focusMonth, -1); break;
      case 'PageDown': moveMonthFocus(focusMonth, 1); break;
      case 'Enter':
      case ' ': openMonth(focusMonth); break;
      case 'Escape': closePanel(true); break;
      default: handled = false;
    }
    if (handled) e.preventDefault();
  }

  function moveFocus(next: Date): void {
    setFocusDate(next);
    setViewMonth(new Date(next.getFullYear(), next.getMonth(), 1));
    pendingFocusRef.current = toISO(next);
  }

  function pick(d: Date): void {
    if (isDayDisabled(d)) return;
    const day: Date = startOfDay(d);
    setFocusDate(day);
    const iso: string = toISO(day);
    props.onChange(iso);
    closePanel(true);
  }

  // Clear (reset to empty). Calls onChange('') — parseISO('') is null, so the placeholder shows again.
  function clearValue(): void {
    props.onChange('');
    setOpen(false);
    triggerRef.current?.focus();
  }

  function openPanel(): void {
    if (isDisabled || isReadonly || open) return;
    const next: Date = selectedDate ?? focusDate ?? new Date();
    setFocusDate(next);
    setViewMonth(new Date(next.getFullYear(), next.getMonth(), 1));
    setOpen(true);
    pendingFocusRef.current = toISO(next);
  }

  function closePanel(returnFocus: boolean): void {
    if (!open) return;
    setOpen(false);
    if (returnFocus) triggerRef.current?.focus();
  }

  function toggle(): void {
    if (open) closePanel(false);
    else openPanel();
  }

  function onGridKeydown(e: React.KeyboardEvent<HTMLDivElement>): void {
    const f: Date = effectiveFocusDate;
    switch (e.key) {
      case 'ArrowLeft':
        e.preventDefault();
        moveFocus(addDays(f, -1));
        break;
      case 'ArrowRight':
        e.preventDefault();
        moveFocus(addDays(f, 1));
        break;
      case 'ArrowUp':
        e.preventDefault();
        moveFocus(addDays(f, -7));
        break;
      case 'ArrowDown':
        e.preventDefault();
        moveFocus(addDays(f, 7));
        break;
      case 'Home':
        e.preventDefault();
        moveFocus(addDays(f, -((f.getDay() + 6) % 7)));
        break;
      case 'End':
        e.preventDefault();
        moveFocus(addDays(f, 6 - ((f.getDay() + 6) % 7)));
        break;
      case 'PageUp':
        e.preventDefault();
        moveFocus(addMonths(f, e.shiftKey ? -12 : -1));
        break;
      case 'PageDown':
        e.preventDefault();
        moveFocus(addMonths(f, e.shiftKey ? 12 : 1));
        break;
      case 'Enter':
      case ' ':
        e.preventDefault();
        pick(f);
        break;
      case 'Escape':
        e.preventDefault();
        closePanel(true);
        break;
      default:
        break;
    }
  }

  // Close when focus leaves the control entirely (e.g. Shift+Tab off the trigger).
  /* A null relatedTarget means focus fell to <body> — which is what happens when the element the
     user just pressed is REMOVED by the click it triggered (drilling into the month grid replaces
     the grid, and with it the cell that had focus). That is not focus leaving the control, and
     closing on it made the panel vanish mid-navigation. A pointer that really lands outside is
     handled by the mousedown listener, which is the reliable path for that case. */
  const onFocusout = (e: React.FocusEvent<HTMLDivElement>): void => {
    const next: EventTarget | null = e.relatedTarget;
    if (next === null) return;
    if (rootRef.current !== null && !(next instanceof Node && rootRef.current.contains(next))) closePanel(false);
  };

  // Close when a pointer lands outside the whole control.
  useEffect((): void | (() => void) => {
    if (!open) return;
    const onDocPointerDown = (e: MouseEvent): void => {
      const t: EventTarget | null = e.target;
      if (rootRef.current !== null && t instanceof Node && !rootRef.current.contains(t)) closePanel(false);
    };
    document.addEventListener('mousedown', onDocPointerDown);
    return (): void => document.removeEventListener('mousedown', onDocPointerDown);
  }, [open]);

  return (
    <div ref={rootRef} className={isInvalid ? 'fdy-datepicker fdy-datepicker--error' : 'fdy-datepicker'} onBlur={onFocusout}>
      <button
        id={triggerId}
        ref={triggerRef}
        type="button"
        className={open ? 'fdy-datepicker__trigger is-open' : 'fdy-datepicker__trigger'}
        aria-haspopup="dialog"
        aria-expanded={open}
        aria-labelledby={props.ariaLabelledby}
        aria-invalid={isInvalid ? 'true' : undefined}
        aria-readonly={isReadonly ? 'true' : undefined}
        aria-describedby={props.describedby}
        disabled={isDisabled}
        onClick={toggle}
      >
        <span className={selectedDate === null ? 'fdy-datepicker__value fdy-datepicker__value--placeholder' : 'fdy-datepicker__value'}>
          {displayValue}
        </span>
        <span className={showClear ? 'fdy-datepicker__icon is-hidden' : 'fdy-datepicker__icon'} aria-hidden="true">
          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2} strokeLinecap="round" strokeLinejoin="round">
            <rect x="3" y="4" width="18" height="18" rx="2"></rect>
            <path d="M16 2v4M8 2v4M3 10h18"></path>
          </svg>
        </span>
      </button>
      {showClear ? (
        <button
          type="button"
          className="fdy-datepicker__clear"
          aria-label={clearLabelText}
          onMouseDown={(e: React.MouseEvent): void => e.preventDefault()}
          onClick={clearValue}
        >
          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2} strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
            <path d="M18 6 6 18M6 6l12 12"></path>
          </svg>
        </button>
      ) : null}

      <div ref={panelRef} className="fdy-datepicker__panel" role="dialog" aria-modal="false" aria-labelledby={titleId} hidden={!open}>
        {/* ONE head for both modes on purpose: swapping it destroys the very button the user just
            pressed, focus falls to <body>, and the panel's own focusout handler closes it. */}
        <div className="fdy-cal__head">
          <button
            type="button"
            className="fdy-cal__nav"
            aria-label={mode === 'years' ? prevYearsLabelText : mode === 'months' ? prevYearLabelText : prevMonthLabelText}
            onClick={(): void => {
              if (mode === 'years') moveYearFocus(focusYear - YEARS_PER_PAGE);
              else if (mode === 'months') moveMonthFocus(focusMonth, -1);
              else setViewMonth(addMonths(viewMonth, -1));
            }}
          >
            &lsaquo;
          </button>
          <button
            id={titleId}
            type="button"
            className="fdy-cal__title"
            aria-label={mode === 'years' ? undefined : mode === 'months' ? chooseYearLabelText : chooseMonthLabelText}
            onClick={(): void => { if (mode === 'months') openYearGrid(); else openMonthGrid(); }}
          >
            {mode === 'years' ? yearRangeLabel : mode === 'months' ? String(viewMonth.getFullYear()) : monthFmt.format(viewMonth)}
          </button>
          <button
            type="button"
            className="fdy-cal__nav"
            aria-label={mode === 'years' ? nextYearsLabelText : mode === 'months' ? nextYearLabelText : nextMonthLabelText}
            onClick={(): void => {
              if (mode === 'years') moveYearFocus(focusYear + YEARS_PER_PAGE);
              else if (mode === 'months') moveMonthFocus(focusMonth, 1);
              else setViewMonth(addMonths(viewMonth, 1));
            }}
          >
            &rsaquo;
          </button>
        </div>
        {mode === 'years' ? (
          <div className="fdy-cal__grid fdy-cal__grid--years" role="grid" aria-labelledby={titleId} onKeyDown={onYearKeydown}>
            {yearCells.map((cell: YearCell) => (
              <button
                key={cell.year}
                ref={(el: HTMLButtonElement | null): void => { yearRefs.current[cell.year] = el; }}
                type="button"
                className={['fdy-cal__year', cell.today ? 'is-today' : '', cell.selected ? 'is-selected' : ''].filter(Boolean).join(' ')}
                role="gridcell"
                aria-label={String(cell.year)}
                aria-selected={cell.selected ? true : undefined}
                disabled={cell.disabled}
                tabIndex={cell.focusable ? 0 : -1}
                onClick={(): void => openYear(cell.year)}
              >
                {cell.year}
              </button>
            ))}
          </div>
        ) : mode === 'months' ? (
          <div className="fdy-cal__grid fdy-cal__grid--months" role="grid" aria-labelledby={titleId} onKeyDown={onMonthKeydown}>
            {monthCells.map((cell: MonthCell) => (
              <button
                key={cell.index}
                ref={(el: HTMLButtonElement | null): void => { monthRefs.current[cell.index] = el; }}
                type="button"
                className={['fdy-cal__month', cell.today ? 'is-today' : '', cell.selected ? 'is-selected' : ''].filter(Boolean).join(' ')}
                role="gridcell"
                aria-label={cell.ariaLabel}
                aria-selected={cell.selected ? true : undefined}
                disabled={cell.disabled}
                tabIndex={cell.focusable ? 0 : -1}
                onClick={(): void => openMonth(cell.index)}
              >
                {cell.label}
              </button>
            ))}
          </div>
        ) : (
        <div className="fdy-cal__grid" role="grid" aria-labelledby={titleId} onKeyDown={onGridKeydown}>
          {weekdayHeaders.map((w: string): JSX.Element => (
            <div key={w} className="fdy-cal__dow" role="columnheader" aria-label={w}>{w}</div>
          ))}
          {gridCells.map((cell: DayCell): JSX.Element => (
            <button
              key={cell.iso}
              ref={(el: HTMLButtonElement | null): void => {
                dayRefs.current[cell.iso] = el;
              }}
              type="button"
              className={dayClassName(cell)}
              role="gridcell"
              aria-label={cell.ariaLabel}
              aria-selected={cell.selected ? 'true' : undefined}
              disabled={cell.disabled}
              tabIndex={cell.focusable ? 0 : -1}
              onClick={(): void => pick(cell.date)}
            >
              {cell.label}
            </button>
          ))}
        </div>
        )}

      </div>
    </div>
  );
}

// adapters/vue/components/FdyDatepicker.vue
<script setup lang="ts">
import { computed, nextTick, onBeforeUnmount, onMounted, ref, useId, type ComputedRef, type Ref } from 'vue';
import { usePopover } from '../usePopover';

// A Vue-native binding over freeday's `.fdy-datepicker` / `.fdy-cal__*` classes
// (see src/components/datepicker.css). freeday ships the styled trigger+popover
// pair plus a framework-agnostic enhancer (freeday-datepicker.js) whose own
// header says the DOM it builds is meant for markup it owns wholesale. Letting
// that enhancer manage the DOM would fight Vue's rendering, so this component
// re-implements its single-date calendar behavior (month grid, keyboard nav,
// min/max clamping, Intl locale formatting) in Vue, giving a real `v-model`
// over the same kit classes. Open/close (outside-click + focusout) mirrors the
// already-approved FdyCombo.vue pattern. Range mode is out of scope (v1 = single date).

interface DayCell {
  date: Date;
  iso: string;
  label: number;
  ariaLabel: string;
  outside: boolean;
  today: boolean;
  selected: boolean;
  disabled: boolean;
  focusable: boolean;
}

const props = defineProps<{
  modelValue: string | null;
  min?: string;
  max?: string;
  locale?: string;
  placeholder?: string;
  disabled?: boolean;
  /** Locked/view mode: stays focusable and shows its date, but can't be opened, cleared, or changed. Unlike `disabled`, it keeps tab order and isn't greyed. */
  readonly?: boolean;
  invalid?: boolean;
  describedby?: string;
  id?: string;
  ariaLabelledby?: string;
  /** Show a clear (×) button in the trigger when a date is set, so an optional date can be unset. Emits `''` via update:modelValue + change. Off by default. */
  clearable?: boolean;
  /** aria-label for the previous-month nav button. Default 'Previous month' — override for non-English UIs (month/weekday names already follow `locale`). */
  prevMonthLabel?: string;
  /** aria-label for the next-month nav button. Default 'Next month'. */
  nextMonthLabel?: string;
  /** aria-label for the clear button (when `clearable`). Default 'Clear date'. */
  clearLabel?: string;
  /** aria-label for the title button that drills to the month grid. Default 'Choose month'. */
  chooseMonthLabel?: string;
  /** aria-labels for the year arrows shown in the month grid. Defaults 'Previous year' / 'Next year'. */
  prevYearLabel?: string;
  nextYearLabel?: string;
  /** aria-label for the title button that drills from the month grid to the year grid. Default 'Choose year'. */
  chooseYearLabel?: string;
  /** aria-labels for the page arrows shown in the year grid. Defaults 'Previous years' / 'Next years'. */
  prevYearsLabel?: string;
  nextYearsLabel?: string;
}>();

const emit = defineEmits<{
  'update:modelValue': [value: string];
  change: [value: string];
}>();

function pad(n: number): string {
  return n < 10 ? `0${n}` : `${n}`;
}
function toISO(d: Date): string {
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}`;
}
function parseISO(s: string | null | undefined): Date | null {
  if (s === null || s === undefined || s === '') return null;
  const parts: string[] = s.split('-');
  if (parts.length !== 3) return null;
  const y: number = Number(parts[0]);
  const m: number = Number(parts[1]);
  const day: number = Number(parts[2]);
  const d: Date = new Date(y, m - 1, day);
  return Number.isNaN(d.getTime()) ? null : d;
}
function startOfDay(d: Date): Date {
  return new Date(d.getFullYear(), d.getMonth(), d.getDate());
}
function startOfMonth(d: Date): Date {
  return new Date(d.getFullYear(), d.getMonth(), 1);
}
function sameDay(a: Date | null, b: Date | null): boolean {
  return a !== null && b !== null && a.getFullYear() === b.getFullYear() && a.getMonth() === b.getMonth() && a.getDate() === b.getDate();
}
function addDays(d: Date, n: number): Date {
  const x: Date = new Date(d);
  x.setDate(x.getDate() + n);
  return x;
}
function addMonths(d: Date, n: number): Date {
  const x: Date = new Date(d);
  x.setMonth(x.getMonth() + n);
  return x;
}

const baseId: string = useId();
const triggerId: ComputedRef<string> = computed((): string => props.id ?? `${baseId}-trigger`);
const titleId: string = `${baseId}-title`;

const rootEl: Ref<HTMLDivElement | null> = ref(null);
const triggerEl: Ref<HTMLButtonElement | null> = ref(null);
const panelEl: Ref<HTMLDivElement | null> = ref(null);
const dayRefs: Record<string, HTMLButtonElement | null> = {};

const open: Ref<boolean> = ref(false);

// Render the calendar panel in the top layer (popover) so it never gets clipped by a card or
// scroll container; positions against the trigger.
usePopover(panelEl, triggerEl, open);

const selectedDate: ComputedRef<Date | null> = computed((): Date | null => parseISO(props.modelValue));
const minDate: ComputedRef<Date | null> = computed((): Date | null => parseISO(props.min));
const maxDate: ComputedRef<Date | null> = computed((): Date | null => parseISO(props.max));
const isDisabled: ComputedRef<boolean> = computed((): boolean => props.disabled === true);
const isReadonly: ComputedRef<boolean> = computed((): boolean => props.readonly === true);
const isInvalid: ComputedRef<boolean> = computed((): boolean => props.invalid === true);
const displayPlaceholder: ComputedRef<string> = computed((): string => props.placeholder ?? 'Select date');
const showClear: ComputedRef<boolean> = computed(
  (): boolean => props.clearable === true && selectedDate.value !== null && isDisabled.value === false && isReadonly.value === false,
);
const prevMonthLabelText: ComputedRef<string> = computed((): string => props.prevMonthLabel ?? 'Previous month');
const nextMonthLabelText: ComputedRef<string> = computed((): string => props.nextMonthLabel ?? 'Next month');
const clearLabelText: ComputedRef<string> = computed((): string => props.clearLabel ?? 'Clear date');
const chooseMonthLabelText: ComputedRef<string> = computed((): string => props.chooseMonthLabel ?? 'Choose month');
const prevYearLabelText: ComputedRef<string> = computed((): string => props.prevYearLabel ?? 'Previous year');
const nextYearLabelText: ComputedRef<string> = computed((): string => props.nextYearLabel ?? 'Next year');
const chooseYearLabelText: ComputedRef<string> = computed((): string => props.chooseYearLabel ?? 'Choose year');
const prevYearsLabelText: ComputedRef<string> = computed((): string => props.prevYearsLabel ?? 'Previous years');
const nextYearsLabelText: ComputedRef<string> = computed((): string => props.nextYearsLabel ?? 'Next years');

const view: Ref<Date> = ref(startOfMonth(selectedDate.value ?? new Date()));
const focusDate: Ref<Date> = ref(selectedDate.value ?? new Date());

// Keep the roving-tabindex cell inside the visible month so the grid stays keyboard-reachable
// after navigating with Home/End/PageUp/PageDown (mirrors freeday-datepicker.js's clamp).
const effectiveFocusDate: ComputedRef<Date> = computed((): Date => {
  const f: Date = focusDate.value;
  if (f.getMonth() === view.value.getMonth() && f.getFullYear() === view.value.getFullYear()) return f;
  const daysInMonth: number = new Date(view.value.getFullYear(), view.value.getMonth() + 1, 0).getDate();
  return new Date(view.value.getFullYear(), view.value.getMonth(), Math.min(f.getDate(), daysInMonth));
});

/* 'days' | 'months' — the calendar drills one level up instead of growing furniture beside the title.
   Before this the only pointer route to another month was one click per month: August 2026 to March
   2022 is fifty-three of them, and the Shift+PageUp jump had no affordance at all. */
const mode: Ref<'days' | 'months' | 'years'> = ref('days');
const focusMonth: Ref<number> = ref(0);
const focusYear: Ref<number> = ref(0);

/* A page of twelve years, ALIGNED so pages tile: 2016-2027, 2028-2039. Anchoring the page on the
   year in view would make the arrows land on overlapping windows, and the same year would sit at a
   different spot every time you stepped. */
const YEARS_PER_PAGE = 12;
const yearPageStart = (year: number): number => Math.floor(year / YEARS_PER_PAGE) * YEARS_PER_PAGE;

const monthCellFmt: ComputedRef<Intl.DateTimeFormat> = computed(
  (): Intl.DateTimeFormat => new Intl.DateTimeFormat(props.locale, { month: 'short' }),
);
const monthNameFmt: ComputedRef<Intl.DateTimeFormat> = computed(
  (): Intl.DateTimeFormat => new Intl.DateTimeFormat(props.locale, { month: 'long', year: 'numeric' }),
);

interface MonthCell {
  index: number;
  label: string;
  ariaLabel: string;
  selected: boolean;
  today: boolean;
  disabled: boolean;
  focusable: boolean;
}

/** A month is only unreachable when the WHOLE month falls outside min/max. Checked against the
 *  bounds directly, not by testing both ends with isDayDisabled: a range that sits INSIDE one month
 *  disables both ends while the middle is perfectly selectable. */
function isMonthDisabled(year: number, month: number): boolean {
  const first: Date = new Date(year, month, 1);
  const last: Date = new Date(year, month + 1, 0);
  if (minDate.value !== null && startOfDay(last).getTime() < startOfDay(minDate.value).getTime()) return true;
  if (maxDate.value !== null && startOfDay(first).getTime() > startOfDay(maxDate.value).getTime()) return true;
  return false;
}

const monthCells: ComputedRef<MonthCell[]> = computed((): MonthCell[] => {
  const year: number = view.value.getFullYear();
  const today: Date = new Date();
  const sel: Date | null = selectedDate.value;
  return Array.from({ length: 12 }, (_unused: unknown, index: number): MonthCell => {
    const cellDate: Date = new Date(year, index, 1);
    return {
      index,
      label: monthCellFmt.value.format(cellDate),
      ariaLabel: monthNameFmt.value.format(cellDate),
      selected: sel !== null && sel.getFullYear() === year && sel.getMonth() === index,
      today: today.getFullYear() === year && today.getMonth() === index,
      disabled: isMonthDisabled(year, index),
      focusable: index === focusMonth.value,
    };
  });
});

interface YearCell {
  year: number;
  selected: boolean;
  today: boolean;
  disabled: boolean;
  focusable: boolean;
}

/** A year is unreachable only when EVERY month in it falls outside min/max — the same rule
 *  isMonthDisabled applies one level down, and for the same reason. */
function isYearDisabled(year: number): boolean {
  if (minDate.value !== null && startOfDay(new Date(year, 11, 31)).getTime() < startOfDay(minDate.value).getTime()) return true;
  if (maxDate.value !== null && startOfDay(new Date(year, 0, 1)).getTime() > startOfDay(maxDate.value).getTime()) return true;
  return false;
}

const yearPage: ComputedRef<number> = computed((): number => yearPageStart(focusYear.value));

const yearCells: ComputedRef<YearCell[]> = computed((): YearCell[] => {
  const start: number = yearPage.value;
  const thisYear: number = new Date().getFullYear();
  const sel: Date | null = selectedDate.value;
  return Array.from({ length: YEARS_PER_PAGE }, (_unused: unknown, index: number): YearCell => {
    const year: number = start + index;
    return {
      year,
      selected: sel !== null && sel.getFullYear() === year,
      today: thisYear === year,
      disabled: isYearDisabled(year),
      focusable: year === focusYear.value,
    };
  });
});

const yearRangeLabel: ComputedRef<string> = computed(
  (): string => `${yearPage.value} – ${yearPage.value + YEARS_PER_PAGE - 1}`,
);

const monthFmt: ComputedRef<Intl.DateTimeFormat> = computed(
  (): Intl.DateTimeFormat => new Intl.DateTimeFormat(props.locale, { month: 'long', year: 'numeric' }),
);
const valueFmt: ComputedRef<Intl.DateTimeFormat> = computed(
  (): Intl.DateTimeFormat => new Intl.DateTimeFormat(props.locale, { day: '2-digit', month: 'short', year: 'numeric' }),
);
const dayLabelFmt: ComputedRef<Intl.DateTimeFormat> = computed(
  (): Intl.DateTimeFormat => new Intl.DateTimeFormat(props.locale, { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' }),
);
const dowFmt: ComputedRef<Intl.DateTimeFormat> = computed(
  (): Intl.DateTimeFormat => new Intl.DateTimeFormat(props.locale, { weekday: 'short' }),
);

const displayValue: ComputedRef<string> = computed((): string =>
  selectedDate.value !== null ? valueFmt.value.format(selectedDate.value) : displayPlaceholder.value,
);

const weekdayHeaders: ComputedRef<string[]> = computed((): string[] => {
  const monday: Date = new Date(2024, 0, 1); // a known Monday
  return Array.from({ length: 7 }, (_unused: unknown, i: number): string => dowFmt.value.format(addDays(monday, i)));
});

function isDayDisabled(d: Date): boolean {
  if (minDate.value !== null && startOfDay(d).getTime() < startOfDay(minDate.value).getTime()) return true;
  if (maxDate.value !== null && startOfDay(d).getTime() > startOfDay(maxDate.value).getTime()) return true;
  return false;
}

const gridCells: ComputedRef<DayCell[]> = computed((): DayCell[] => {
  const first: Date = new Date(view.value.getFullYear(), view.value.getMonth(), 1);
  const offset: number = (first.getDay() + 6) % 7; // Monday-first
  const startCell: Date = addDays(first, -offset);
  const today: Date = new Date();
  const focus: Date = effectiveFocusDate.value;
  const cells: DayCell[] = [];
  for (let i = 0; i < 42; i++) {
    const d: Date = addDays(startCell, i);
    cells.push({
      date: d,
      iso: toISO(d),
      label: d.getDate(),
      ariaLabel: dayLabelFmt.value.format(d),
      outside: d.getMonth() !== view.value.getMonth(),
      today: sameDay(d, today),
      selected: sameDay(d, selectedDate.value),
      disabled: isDayDisabled(d),
      focusable: sameDay(d, focus),
    });
  }
  return cells;
});

function setDayRef(iso: string, el: Element | null): void {
  dayRefs[iso] = el as HTMLButtonElement | null;
}

function focusCell(): void {
  dayRefs[toISO(effectiveFocusDate.value)]?.focus();
}

function moveFocus(next: Date): void {
  focusDate.value = next;
  view.value = new Date(next.getFullYear(), next.getMonth(), 1);
  void nextTick((): void => focusCell());
}

function openMonthGrid(): void {
  focusMonth.value = view.value.getMonth();
  mode.value = 'months';
  void nextTick((): void => focusMonthCell());
}

function focusMonthCell(): void {
  const cell: HTMLElement | null = panelEl.value?.querySelector('.fdy-cal__month[tabindex="0"]') ?? null;
  cell?.focus();
}

/* Picking a month is NAVIGATION, not selection: it drops back to the day grid with the roving cell
   clamped into the new month, so nothing is committed until a day is chosen. */
function openMonth(index: number): void {
  const year: number = view.value.getFullYear();
  const daysInMonth: number = new Date(year, index + 1, 0).getDate();
  const day: number = Math.min(focusDate.value.getDate(), daysInMonth);
  view.value = new Date(year, index, 1);
  focusDate.value = new Date(year, index, day);
  mode.value = 'days';
  void nextTick((): void => focusCell());
}

function openYearGrid(): void {
  focusYear.value = view.value.getFullYear();
  mode.value = 'years';
  void nextTick((): void => focusYearCell());
}

function focusYearCell(): void {
  const cell: HTMLElement | null = panelEl.value?.querySelector('.fdy-cal__year[tabindex="0"]') ?? null;
  cell?.focus();
}

/* Picking a year is NAVIGATION, exactly like picking a month: it drops to that year's month grid
   and commits nothing. */
function openYear(year: number): void {
  view.value = new Date(year, view.value.getMonth(), 1);
  focusMonth.value = view.value.getMonth();
  mode.value = 'months';
  void nextTick((): void => focusMonthCell());
}

function moveYearFocus(year: number): void {
  focusYear.value = year;
  view.value = new Date(year, view.value.getMonth(), 1);
  void nextTick((): void => focusYearCell());
}

function onYearKeydown(e: KeyboardEvent): void {
  let handled: boolean = true;
  switch (e.key) {
    case 'ArrowLeft': moveYearFocus(focusYear.value - 1); break;
    case 'ArrowRight': moveYearFocus(focusYear.value + 1); break;
    case 'ArrowUp': moveYearFocus(focusYear.value - 3); break;
    case 'ArrowDown': moveYearFocus(focusYear.value + 3); break;
    case 'Home': moveYearFocus(yearPageStart(focusYear.value)); break;
    case 'End': moveYearFocus(yearPageStart(focusYear.value) + YEARS_PER_PAGE - 1); break;
    case 'PageUp': moveYearFocus(focusYear.value - YEARS_PER_PAGE); break;
    case 'PageDown': moveYearFocus(focusYear.value + YEARS_PER_PAGE); break;
    case 'Enter':
    case ' ': openYear(focusYear.value); break;
    case 'Escape': closePanel(true); break;
    default: handled = false;
  }
  if (handled) { e.preventDefault(); e.stopPropagation(); }
}

function moveMonthFocus(index: number, yearDelta: number): void {
  if (yearDelta !== 0) view.value = addMonths(view.value, yearDelta * 12);
  focusMonth.value = (index + 12) % 12;
  void nextTick((): void => focusMonthCell());
}

function onMonthKeydown(e: KeyboardEvent): void {
  let handled: boolean = true;
  switch (e.key) {
    case 'ArrowLeft': moveMonthFocus(focusMonth.value - 1, 0); break;
    case 'ArrowRight': moveMonthFocus(focusMonth.value + 1, 0); break;
    case 'ArrowUp': moveMonthFocus(focusMonth.value - 3, 0); break;
    case 'ArrowDown': moveMonthFocus(focusMonth.value + 3, 0); break;
    case 'Home': moveMonthFocus(0, 0); break;
    case 'End': moveMonthFocus(11, 0); break;
    case 'PageUp': moveMonthFocus(focusMonth.value, -1); break;
    case 'PageDown': moveMonthFocus(focusMonth.value, 1); break;
    case 'Enter':
    case ' ': openMonth(focusMonth.value); break;
    case 'Escape': closePanel(true); break;
    default: handled = false;
  }
  if (handled) e.preventDefault();
}

function pick(d: Date): void {
  if (isDayDisabled(d)) return;
  const day: Date = startOfDay(d);
  focusDate.value = day;
  const iso: string = toISO(day);
  emit('update:modelValue', iso);
  emit('change', iso);
  closePanel(true);
}

// Clear (reset to empty). Emits '' — parseISO('') is null, so the placeholder shows again.
function clearValue(): void {
  emit('update:modelValue', '');
  emit('change', '');
  open.value = false;
  triggerEl.value?.focus();
}

function openPanel(): void {
  if (isDisabled.value || isReadonly.value || open.value) return;
  focusDate.value = selectedDate.value ?? focusDate.value ?? new Date();
  view.value = new Date(focusDate.value.getFullYear(), focusDate.value.getMonth(), 1);
  open.value = true;
  void nextTick((): void => focusCell());
}

function closePanel(returnFocus: boolean): void {
  if (!open.value) return;
  open.value = false;
  if (returnFocus) triggerEl.value?.focus();
}

function toggle(): void {
  if (open.value) closePanel(false);
  else openPanel();
}

function onGridKeydown(e: KeyboardEvent): void {
  const f: Date = effectiveFocusDate.value;
  switch (e.key) {
    case 'ArrowLeft':
      e.preventDefault();
      moveFocus(addDays(f, -1));
      break;
    case 'ArrowRight':
      e.preventDefault();
      moveFocus(addDays(f, 1));
      break;
    case 'ArrowUp':
      e.preventDefault();
      moveFocus(addDays(f, -7));
      break;
    case 'ArrowDown':
      e.preventDefault();
      moveFocus(addDays(f, 7));
      break;
    case 'Home':
      e.preventDefault();
      moveFocus(addDays(f, -((f.getDay() + 6) % 7)));
      break;
    case 'End':
      e.preventDefault();
      moveFocus(addDays(f, 6 - ((f.getDay() + 6) % 7)));
      break;
    case 'PageUp':
      e.preventDefault();
      moveFocus(addMonths(f, e.shiftKey ? -12 : -1));
      break;
    case 'PageDown':
      e.preventDefault();
      moveFocus(addMonths(f, e.shiftKey ? 12 : 1));
      break;
    case 'Enter':
    case ' ':
      e.preventDefault();
      pick(f);
      break;
    case 'Escape':
      e.preventDefault();
      closePanel(true);
      break;
    default:
      break;
  }
}

// Close when a pointer lands outside the whole control.
function onDocPointerDown(e: MouseEvent): void {
  const target: EventTarget | null = e.target;
  if (rootEl.value !== null && target instanceof Node && !rootEl.value.contains(target)) {
    closePanel(false);
  }
}

// Close when focus leaves the control entirely (e.g. Shift+Tab off the trigger).
/* A null relatedTarget means focus fell to <body>, which is what happens when the element the
 * user just pressed is REMOVED by the click it triggered (drilling into the month grid replaces
 * the grid, and with it the cell that had focus). That is not focus leaving the control, and
 * closing on it made the panel vanish mid-navigation. A pointer that really lands outside is
 * handled by the mousedown listener, which is the reliable path for that case. */
function onFocusout(e: FocusEvent): void {
  const next: EventTarget | null = e.relatedTarget;
  if (next === null) return;
  if (rootEl.value !== null && !(next instanceof Node && rootEl.value.contains(next))) {
    closePanel(false);
  }
}

onMounted((): void => {
  document.addEventListener('mousedown', onDocPointerDown);
});
onBeforeUnmount((): void => {
  document.removeEventListener('mousedown', onDocPointerDown);
});
</script>

<template>
  <div ref="rootEl" class="fdy-datepicker" :class="{ 'fdy-datepicker--error': isInvalid }" @focusout="onFocusout">
    <button
      :id="triggerId"
      ref="triggerEl"
      type="button"
      class="fdy-datepicker__trigger"
      :class="{ 'is-open': open }"
      aria-haspopup="dialog"
      :aria-expanded="open"
      :aria-labelledby="ariaLabelledby"
      :aria-invalid="isInvalid ? 'true' : undefined"
      :aria-readonly="isReadonly ? 'true' : undefined"
      :aria-describedby="describedby"
      :disabled="isDisabled"
      @click="toggle"
    >
      <span class="fdy-datepicker__value" :class="{ 'fdy-datepicker__value--placeholder': selectedDate === null }">{{ displayValue }}</span>
      <span class="fdy-datepicker__icon" :class="{ 'is-hidden': showClear }" aria-hidden="true">
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
          <rect x="3" y="4" width="18" height="18" rx="2"></rect>
          <path d="M16 2v4M8 2v4M3 10h18"></path>
        </svg>
      </span>
    </button>
    <button
      v-if="showClear"
      type="button"
      class="fdy-datepicker__clear"
      :aria-label="clearLabelText"
      @mousedown.prevent
      @click="clearValue"
    >
      <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
        <path d="M18 6 6 18M6 6l12 12"></path>
      </svg>
    </button>

    <div ref="panelEl" class="fdy-datepicker__panel" role="dialog" aria-modal="false" popover="manual" :aria-labelledby="titleId" :hidden="!open">
      <!-- ONE head for both modes on purpose: swapping it with v-if destroys the very button the user
           just pressed, focus falls to <body>, and the panel's own focusout handler closes it. The
           labels and handlers switch; the elements do not. -->
      <div class="fdy-cal__head">
        <button
          type="button"
          class="fdy-cal__nav"
          :aria-label="mode === 'years' ? prevYearsLabelText : mode === 'months' ? prevYearLabelText : prevMonthLabelText"
          @click="
            mode === 'years'
              ? moveYearFocus(focusYear - 12)
              : mode === 'months'
                ? moveMonthFocus(focusMonth, -1)
                : (view = addMonths(view, -1))
          "
        >‹</button>
        <button
          :id="titleId"
          type="button"
          class="fdy-cal__title"
          :aria-label="mode === 'years' ? undefined : mode === 'months' ? chooseYearLabelText : chooseMonthLabelText"
          @click="mode === 'months' ? openYearGrid() : openMonthGrid()"
        >{{ mode === 'years' ? yearRangeLabel : mode === 'months' ? String(view.getFullYear()) : monthFmt.format(view) }}</button>
        <button
          type="button"
          class="fdy-cal__nav"
          :aria-label="mode === 'years' ? nextYearsLabelText : mode === 'months' ? nextYearLabelText : nextMonthLabelText"
          @click="
            mode === 'years'
              ? moveYearFocus(focusYear + 12)
              : mode === 'months'
                ? moveMonthFocus(focusMonth, 1)
                : (view = addMonths(view, 1))
          "
        >›</button>
      </div>
      <div v-if="mode === 'years'" class="fdy-cal__grid fdy-cal__grid--years" role="grid" :aria-labelledby="titleId" @keydown="onYearKeydown">
        <button
          v-for="cell in yearCells"
          :key="cell.year"
          type="button"
          class="fdy-cal__year"
          :class="{ 'is-today': cell.today, 'is-selected': cell.selected }"
          role="gridcell"
          :aria-label="String(cell.year)"
          :aria-selected="cell.selected ? 'true' : undefined"
          :disabled="cell.disabled"
          :tabindex="cell.focusable ? 0 : -1"
          @click="openYear(cell.year)"
        >{{ cell.year }}</button>
      </div>
      <div v-else-if="mode === 'months'" class="fdy-cal__grid fdy-cal__grid--months" role="grid" :aria-labelledby="titleId" @keydown="onMonthKeydown">
        <button
          v-for="cell in monthCells"
          :key="cell.index"
          type="button"
          class="fdy-cal__month"
          :class="{ 'is-today': cell.today, 'is-selected': cell.selected }"
          role="gridcell"
          :aria-label="cell.ariaLabel"
          :aria-selected="cell.selected ? 'true' : undefined"
          :disabled="cell.disabled"
          :tabindex="cell.focusable ? 0 : -1"
          @click="openMonth(cell.index)"
        >{{ cell.label }}</button>
      </div>
      <div v-else class="fdy-cal__grid" role="grid" :aria-labelledby="titleId" @keydown="onGridKeydown">
        <div v-for="w in weekdayHeaders" :key="w" class="fdy-cal__dow" role="columnheader" :aria-label="w">{{ w }}</div>
        <button
          v-for="cell in gridCells"
          :key="cell.iso"
          :ref="(el) => setDayRef(cell.iso, el as Element | null)"
          type="button"
          class="fdy-cal__day"
          :class="{ 'is-outside': cell.outside, 'is-today': cell.today, 'is-selected': cell.selected }"
          role="gridcell"
          :aria-label="cell.ariaLabel"
          :aria-selected="cell.selected ? 'true' : undefined"
          :disabled="cell.disabled"
          :tabindex="cell.focusable ? 0 : -1"
          @click="pick(cell.date)"
        >{{ cell.label }}</button>
      </div>
    </div>
  </div>
</template>
