// adapters/react/components/FdyModal.tsx
import type { JSX, ReactNode } from 'react';
import { useEffect, useId, useRef } from 'react';

// A controlled React wrapper over freeday's `.fdy-modal` native <dialog> (src/components/modal.css).
// React port of adapters/vue/components/FdyModal.vue: reconciles the reactive `open` boolean with a
// DOM element whose open/close is a method call — showModal()/close() guarded against the
// already-open/closed cases (showModal() on an open dialog throws), onCancel + preventDefault so Esc
// routes through app state instead of closing the DOM behind its back, and backdrop-click detection
// via `event.target === dialogEl`. Native <dialog> already gives the focus trap, focus restore,
// top-layer stacking and inert background. `dismissible` (default true) gates Esc + backdrop.

export interface FdyModalProps {
  open: boolean;
  title: ReactNode;
  onClose: () => void;
  size?: 'sm' | 'md' | 'lg' | 'wide';
  dismissible?: boolean;
  footer?: ReactNode;
  children?: ReactNode;
}

export function FdyModal(props: FdyModalProps): JSX.Element {
  const dialogRef = useRef<HTMLDialogElement>(null);
  const titleId: string = `${useId()}-title`;
  const dismissible: boolean = props.dismissible !== false;
  const modalClass: string = props.size !== undefined ? `fdy-modal fdy-modal--${props.size}` : 'fdy-modal';

  // Reconcile `open` with the dialog's method-driven state (runs on mount and whenever open changes).
  // showModal() on an already-open dialog throws, so guard both directions.
  useEffect((): void => {
    const el: HTMLDialogElement | null = dialogRef.current;
    if (el === null) return;
    if (props.open && !el.open) el.showModal();
    else if (!props.open && el.open) el.close();
  }, [props.open]);

  return (
    <dialog
      ref={dialogRef}
      className={modalClass}
      aria-labelledby={titleId}
      onCancel={(e): void => {
        e.preventDefault(); // stop the native close; app state stays the single source of truth
        if (dismissible) props.onClose();
      }}
      onClick={(e): void => {
        // The ::backdrop is not a separate element — target === the dialog box means a backdrop click.
        if (dismissible && e.target === dialogRef.current) props.onClose();
      }}
    >
      <div className="fdy-modal__header">
        <h3 id={titleId} className="fdy-modal__title">{props.title}</h3>
        {dismissible && (
          <button className="fdy-modal__close" type="button" aria-label="Close" onClick={props.onClose}>&times;</button>
        )}
      </div>

      <div className="fdy-modal__body">{props.children}</div>

      {props.footer !== undefined && <div className="fdy-modal__footer">{props.footer}</div>}
    </dialog>
  );
}

// adapters/vue/components/FdyModal.vue
<script setup lang="ts">
import { computed, onMounted, useId, watch, type ComputedRef, type Ref, ref } from 'vue';

// A controlled Vue wrapper over freeday's `.fdy-modal` native <dialog> (src/components/modal.css).
// The kit styles the dialog but nothing drives it; every consumer re-derives the same imperative
// glue to reconcile a reactive `open` boolean with a DOM element whose open/close is a method call.
// This writes that glue once: showModal()/close() guarded against the already-open/closed cases
// (showModal() on an open dialog throws), @cancel.prevent so Esc routes through app state instead of
// closing the DOM behind its back, and backdrop-click detection via `event.target === dialogEl`.
// Native <dialog> already provides the focus trap, focus restore, top-layer stacking and inert
// background — the wrapper only avoids breaking them. `dismissible` (default true) gates Esc + backdrop.

const props = defineProps<{
  open: boolean;
  title: string;
  size?: 'sm' | 'md' | 'lg' | 'wide';
  dismissible?: boolean;
}>();

const emit = defineEmits<{
  close: [];
}>();

const dialogEl: Ref<HTMLDialogElement | null> = ref(null);
const titleId: string = `${useId()}-title`;
const dismissible: ComputedRef<boolean> = computed((): boolean => props.dismissible !== false);
const modalClass: ComputedRef<string> = computed((): string =>
  props.size !== undefined ? `fdy-modal fdy-modal--${props.size}` : 'fdy-modal',
);

// Reconcile the reactive `open` with the dialog's method-driven state. Both guards matter:
// showModal() on an already-open dialog throws; close() on a closed one is a no-op but kept symmetric.
function sync(open: boolean): void {
  const el: HTMLDialogElement | null = dialogEl.value;
  if (el === null) return;
  if (open && !el.open) el.showModal();
  else if (!open && el.open) el.close();
}
watch((): boolean => props.open, sync, { flush: 'post' });
onMounted((): void => sync(props.open));

// Esc fires `cancel`; .prevent stops the native close so app state stays the single source of truth.
function onCancel(): void {
  if (dismissible.value) emit('close');
}
// The ::backdrop is not a separate element — a click whose target is the dialog box itself (not its
// content) is a backdrop click.
function onClick(e: MouseEvent): void {
  if (dismissible.value && e.target === dialogEl.value) emit('close');
}
</script>

<template>
  <dialog
    ref="dialogEl"
    :class="modalClass"
    :aria-labelledby="titleId"
    @cancel.prevent="onCancel"
    @click="onClick"
  >
    <div class="fdy-modal__header">
      <h3 :id="titleId" class="fdy-modal__title">
        <slot name="title">{{ title }}</slot>
      </h3>
      <button v-if="dismissible" class="fdy-modal__close" type="button" aria-label="Close" @click="$emit('close')">&times;</button>
    </div>

    <div class="fdy-modal__body">
      <slot />
    </div>

    <div v-if="$slots.footer" class="fdy-modal__footer">
      <slot name="footer" />
    </div>
  </dialog>
</template>
